<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>0577c465-a87e-421c-88dd-7d5badb2678c</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>
	<ItemGroup>
		<_WebToolingArtifacts Remove="Properties\PublishProfiles\http___10.164.19.22_1080_imsc.pubxml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AntDesign" />
		<PackageReference Include="AntDesign.Charts" />
		<PackageReference Include="AntDesign.ProLayout" />
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="BouncyCastle.Cryptography" />
		<PackageReference Include="FreeRedis" />
		<PackageReference Include="FreeRedis.DistributedCache" />
		<PackageReference Include="FreeSql" />
		<PackageReference Include="FreeSql.Provider.MySql" />
		<PackageReference Include="FreeSql.Repository" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" />
		<PackageReference Include="MQTTnet" />
		<PackageReference Include="SharpCifs.Core" />
		<PackageReference Include="System.Formats.Asn1" />
		<PackageReference Include="System.Private.Uri" />
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="System.Threading.Tasks.Extensions" />
		<PackageReference Include="System.Windows.Extensions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\IIOTS.Util\IIOTS.Util.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\assets\403.svg">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\assets\logo.svg">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>