<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86</Platforms>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.Contrib" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="NetMQ" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IIOTS.Interface\IIOTS.Interface.csproj" />
  </ItemGroup>
</Project>