<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IIOTS.Driver\IIOTS.Driver.csproj" />
  </ItemGroup>
</Project>